import Head from "next/head";
import { ThemeProvider } from "@mui/system";
import DrawerAppBar from "../components/Header/DrawerAppBar";
import { Banner } from "../components/Banner";
import { theme } from "../styles/theme";
import { Footer } from "../components/Footer";
import { Contact } from "../components/Contact";

export default function Home() {
	return (
		<>
			<ThemeProvider theme={theme}>
				<Head>
					<title>Create Next App</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<DrawerAppBar />
				<Banner />
				<Contact />
				<Footer />
			</ThemeProvider>
		</>
	);
}
