import Head from "next/head";
import { ThemeProvider } from "@mui/system";
import DrawerAppBar from "../components/Header/DrawerAppBar";
import { theme } from "../styles/theme";
 
export default function Home() {
	return (
		<>
			<ThemeProvider theme={theme}>
				<Head>
					<title>Create Next App</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<DrawerAppBar />
			</ThemeProvider>
		</>
	);
}
